// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-jtlI03lxJcS0d8rES-2I_j-1-MGqgc',
    appId: '1:686808185076:web:e0426669f47f7c70d786a1',
    messagingSenderId: '686808185076',
    projectId: 'mediaid-ai-d92eb',
    authDomain: 'mediaid-ai-d92eb.firebaseapp.com',
    storageBucket: 'mediaid-ai-d92eb.firebasestorage.app',
    measurementId: 'G-GHF63QRXV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XpAjA2byC7JKOV2h2oj8JXXIzoWfcMI',
    appId: '1:686808185076:android:c08b3a7e6250b926d786a1',
    messagingSenderId: '686808185076',
    projectId: 'mediaid-ai-d92eb',
    storageBucket: 'mediaid-ai-d92eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWzldpQIcTOnOTq4NKIe8mbKjbejx12A8',
    appId: '1:686808185076:ios:1ab34b3af600d104d786a1',
    messagingSenderId: '686808185076',
    projectId: 'mediaid-ai-d92eb',
    storageBucket: 'mediaid-ai-d92eb.firebasestorage.app',
    iosBundleId: 'com.example.mediaidUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWzldpQIcTOnOTq4NKIe8mbKjbejx12A8',
    appId: '1:686808185076:ios:1ab34b3af600d104d786a1',
    messagingSenderId: '686808185076',
    projectId: 'mediaid-ai-d92eb',
    storageBucket: 'mediaid-ai-d92eb.firebasestorage.app',
    iosBundleId: 'com.example.mediaidUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb-jtlI03lxJcS0d8rES-2I_j-1-MGqgc',
    appId: '1:686808185076:web:7df5935a46f63848d786a1',
    messagingSenderId: '686808185076',
    projectId: 'mediaid-ai-d92eb',
    authDomain: 'mediaid-ai-d92eb.firebaseapp.com',
    storageBucket: 'mediaid-ai-d92eb.firebasestorage.app',
    measurementId: 'G-P0KDYBJCFV',
  );
}
